# Generated by Django 3.1 on 2023-02-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftcreate', '0002_auto_20230224_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biddstart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('base_price', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(blank=True, null=True)),
                ('nftdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nftdetails_owner', to='nftcreate.contentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Bidderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('bid_price', models.TextField(blank=True, null=True)),
                ('nftdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nftdetails_buyer', to='nftcreate.contentdetails')),
            ],
        ),
    ]
